### ISSUE TITLE
setup SDK : lerna wont work

### ISSUE THREAD

**Issue by trocca** [XYOracleNetwork/sdk-core-nodejs#276]
Trying to setup the SDK on both Win10 and Ubuntu, in both cases the setup instructions seems not working, there is no lerna.js in the SDK package: "'lerna.json' does not exist".

Any known issue or step missing?

**Comment by pllearns** [comment]
Thanks for reporting this. We are working on updating the documentation with new setup steps. We should have an update in a few days.

**Comment by CryptonightCanada** [comment]
extremely disappointed that you haven't made attempts to change this or fix the documentation... such a waste of time trying to install the Node and client on Linux....  please get your details straight (...i am getting more and more distant from working with the XYO product suite as constantly misled)

**Comment by pllearns** [comment]
Thank you for the feedback. Keep in mind, @CryptonightCanada that the core library is not meant to install a node. It helps other applications that intend to install an XYO node to have the correct components to do so. That said, I did update the documentation. You should take a look at our app-xyo-nodejs for a CLI to start a node. Thanks.

**Comment by pllearns** [comment]
Closing the issue as documentation and direction to use app-xyo-nodejs has been updated.
